// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_jOKibgk_ReD6DsLDEcP5ElCMbN2sNo4',
    appId: '1:680908606851:android:76f867b478180ce74d7ab6',
    messagingSenderId: '680908606851',
    projectId: 'nexly-d2dcc',
    storageBucket: 'nexly-d2dcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvIo8e2NTWsCqDbCbpHJ4FPZ4cEEE3doE',
    appId: '1:680908606851:ios:7aece545c55db7494d7ab6',
    messagingSenderId: '680908606851',
    projectId: 'nexly-d2dcc',
    storageBucket: 'nexly-d2dcc.firebasestorage.app',
    androidClientId: '680908606851-gnp6a2oed4l4el49fngbjggrkbc4mnad.apps.googleusercontent.com',
    iosClientId: '680908606851-snecbj1iqgl031qfhmv99pjn556evkqs.apps.googleusercontent.com',
    iosBundleId: 'tw.com.datapkt.nexly',
  );

}